//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Emsal.DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Objects;
    using System.Data.Objects.DataClasses;
    using System.Linq;
    
    public partial class EmsalDBEntities : DbContext
    {
        public EmsalDBEntities()
            : base("name=EmsalDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<C__MigrationHistory> C__MigrationHistory { get; set; }
        public DbSet<EmsalLog> EmsalLogs { get; set; }
        public DbSet<tblAddress> tblAddresses { get; set; }
        public DbSet<tblAnnouncement> tblAnnouncements { get; set; }
        public DbSet<tblAuthenticatedPart> tblAuthenticatedParts { get; set; }
        public DbSet<tblBranchResponsibility> tblBranchResponsibilities { get; set; }
        public DbSet<tblComMessage> tblComMessages { get; set; }
        public DbSet<tblComMessageAttachment> tblComMessageAttachments { get; set; }
        public DbSet<tblCommunication> tblCommunications { get; set; }
        public DbSet<tblConfirmationMessage> tblConfirmationMessages { get; set; }
        public DbSet<tblContract> tblContracts { get; set; }
        public DbSet<tblDemand_Production> tblDemand_Production { get; set; }
        public DbSet<tblEmployee> tblEmployees { get; set; }
        public DbSet<tblEnumCategory> tblEnumCategories { get; set; }
        public DbSet<tblEnumValue> tblEnumValues { get; set; }
        public DbSet<tblExpertise> tblExpertises { get; set; }
        public DbSet<tblForeign_Organization> tblForeign_Organization { get; set; }
        public DbSet<tblOffer_Production> tblOffer_Production { get; set; }
        public DbSet<tblOrganization> tblOrganizations { get; set; }
        public DbSet<tblParty> tblParties { get; set; }
        public DbSet<tblPerson> tblPersons { get; set; }
        public DbSet<tblPotential_Production> tblPotential_Production { get; set; }
        public DbSet<tblPrivilegedRole> tblPrivilegedRoles { get; set; }
        public DbSet<tblPRM_AdminUnit> tblPRM_AdminUnit { get; set; }
        public DbSet<tblPRM_ASCBranch> tblPRM_ASCBranch { get; set; }
        public DbSet<tblPRM_KTNBranch> tblPRM_KTNBranch { get; set; }
        public DbSet<tblPRM_Thoroughfare> tblPRM_Thoroughfare { get; set; }
        public DbSet<tblProduct_Document> tblProduct_Document { get; set; }
        public DbSet<tblProductAddress> tblProductAddresses { get; set; }
        public DbSet<tblProductCatalog> tblProductCatalogs { get; set; }
        public DbSet<tblProductCatalogControl> tblProductCatalogControls { get; set; }
        public DbSet<tblProduction_Calendar> tblProduction_Calendar { get; set; }
        public DbSet<tblProduction_Document> tblProduction_Document { get; set; }
        public DbSet<tblProductionControl> tblProductionControls { get; set; }
        public DbSet<tblProductPrice> tblProductPrices { get; set; }
        public DbSet<tblProductProfileImage> tblProductProfileImages { get; set; }
        public DbSet<tblPropertyDetail> tblPropertyDetails { get; set; }
        public DbSet<tblPropertyType> tblPropertyTypes { get; set; }
        public DbSet<tblRole> tblRoles { get; set; }
        public DbSet<tblTitle> tblTitles { get; set; }
        public DbSet<tblUser> tblUsers { get; set; }
        public DbSet<tblUserRole> tblUserRoles { get; set; }
        public DbSet<tblContractDetailTemp> tblContractDetailTemps { get; set; }
        public DbSet<tblProductionCalendar> tblProductionCalendars { get; set; }
    
        
    }
}
