//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Emsal.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmsalLog
    {
        public long Id { get; set; }
        public string LogType { get; set; }
        public string ChannelId { get; set; }
        public string RequestId { get; set; }
        public Nullable<System.DateTime> InsertDate { get; set; }
        public string logger { get; set; }
        public string Message { get; set; }
        public string Origin { get; set; }
        public string Loglevel { get; set; }
        public string exception { get; set; }
        public string StackTrace { get; set; }
        public string LineNumber { get; set; }
        public string IpNumber { get; set; }
    }
}
