//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Emsal.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblComMessage
    {
        public long Id { get; set; }
        public Nullable<long> Status { get; set; }
        public Nullable<long> Production_Id { get; set; }
        public Nullable<long> Production_type_eV_Id { get; set; }
        public Nullable<long> LastUpdatedStatus { get; set; }
        public Nullable<long> groupID { get; set; }
        public string message { get; set; }
        public Nullable<long> fromUserID { get; set; }
        public Nullable<long> toUserID { get; set; }
        public string createdUser { get; set; }
        public Nullable<long> createdDate { get; set; }
        public string updatedUser { get; set; }
        public Nullable<long> updatedDate { get; set; }
        public Nullable<long> isRead { get; set; }
    }
}
