//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Emsal.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblContractDetailTemp
    {
        public long Id { get; set; }
        public Nullable<long> offerID { get; set; }
        public string ContractNumber_ { get; set; }
        public Nullable<long> ContractDate { get; set; }
        public Nullable<decimal> product_unit_price { get; set; }
        public Nullable<decimal> product_asc_price { get; set; }
        public Nullable<decimal> product_total_count { get; set; }
        public Nullable<decimal> product_total_price { get; set; }
        public Nullable<long> Status { get; set; }
        public string createdUser { get; set; }
        public Nullable<long> createdDate { get; set; }
        public string updatedUser { get; set; }
        public Nullable<long> updatedDate { get; set; }
        public string description { get; set; }
    }
}
