//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Emsal.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblEvaluation
    {
        public long Id { get; set; }
        public Nullable<long> ParentId { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public Nullable<long> EvumValId { get; set; }
        public Nullable<long> Point { get; set; }
        public Nullable<bool> IsMultiselect { get; set; }
        public Nullable<bool> IsAttachment { get; set; }
        public Nullable<bool> IsNote { get; set; }
        public Nullable<bool> IsQuestion { get; set; }
        public Nullable<bool> IsAnswer { get; set; }
        public Nullable<long> Sort { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<bool> isActive { get; set; }
        public Nullable<long> Status { get; set; }
        public Nullable<long> LastUpdatedStatus { get; set; }
        public string createdUser { get; set; }
        public Nullable<long> createdDate { get; set; }
        public string updatedUser { get; set; }
        public Nullable<long> updatedDate { get; set; }
        public string Number { get; set; }
        public Nullable<long> offerUserTypeEValId { get; set; }
        public Nullable<bool> isRequired { get; set; }
        public Nullable<long> evaluationQuestionLocationEValId { get; set; }
    }
}
