//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Emsal.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblPerson
    {
        public long Id { get; set; }
        public string Name { get; set; }
        public string Surname { get; set; }
        public string FatherName { get; set; }
        public string PinNumber { get; set; }
        public Nullable<long> UserId { get; set; }
        public string gender { get; set; }
        public Nullable<long> birtday { get; set; }
        public Nullable<long> educationLevel_eV_Id { get; set; }
        public Nullable<long> job_eV_Id { get; set; }
        public Nullable<long> address_Id { get; set; }
        public Nullable<long> Status { get; set; }
        public Nullable<long> LastUpdatedStatus { get; set; }
        public string createdUser { get; set; }
        public Nullable<long> createdDate { get; set; }
        public string updatedUser { get; set; }
        public Nullable<long> updatedDate { get; set; }
        public string profilePicture { get; set; }
    }
}
