//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Emsal.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblPrivilegedRole
    {
        public long ID { get; set; }
        public long AuthenticatedPartID { get; set; }
        public long RoleID { get; set; }
        public Nullable<long> Status { get; set; }
    }
}
