//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Emsal.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblProductionCalendar
    {
        public long Id { get; set; }
        public Nullable<long> type_eV_Id { get; set; }
        public Nullable<long> Production_type_eV_Id { get; set; }
        public Nullable<long> Production_Id { get; set; }
        public Nullable<long> day { get; set; }
        public Nullable<long> months_eV_Id { get; set; }
        public Nullable<long> oclock { get; set; }
        public Nullable<decimal> price { get; set; }
        public Nullable<long> demand_Id { get; set; }
        public Nullable<long> offer_Id { get; set; }
        public Nullable<decimal> quantity { get; set; }
        public Nullable<long> Status { get; set; }
        public Nullable<long> LastUpdateStatus { get; set; }
        public string createdUser { get; set; }
        public Nullable<long> createdDate { get; set; }
        public string updatedUser { get; set; }
        public Nullable<long> updatedDate { get; set; }
        public Nullable<long> transportation_eV_Id { get; set; }
        public Nullable<long> year { get; set; }
        public Nullable<long> partOfyear { get; set; }
    }
}
